spring:
  application:
    name: bookmymovie-backend
  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: jdbc:postgresql://bookmymovie.cpk04e8ai2r1.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: dvSD99UMGaAHQTZmPpRB
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # Use 'create-drop' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis Configuration (for later)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # Security Configuration
  security:
    user:
      name: admin
      password: admin123

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: bookmymovie_secret_key_2024_very_long_and_secure_key_here
  expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    org.springframework.boot.autoconfigure.security: DEBUG
    com.bookmymovie: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bookmymovie.log