spring:
  application:
    name: bookmymovie-backend
  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: jdbc:postgresql://bookmymovie.cpr1.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: dvSDpRB
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # Use 'create-drop' for development, 'validate' for production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # Redis Configuration (for later)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

    # Connection pool settings
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 2000ms

# Redisson Configuration
redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      connectionPoolSize: 10
      connectionMinimumIdleSize: 2
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500

# Distributed Lock Configuration
distributed-lock:
  default:
    wait-time: 100          # Default wait time in milliseconds
    lease-time: 5000        # Default lease time in milliseconds
    retry-interval: 50      # Retry interval in milliseconds
    max-retry-attempts: 3   # Maximum retry attempts

  # Security Configuration
  security:
    user:
      name: admin
      password: admin123

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: bookmymovie_secret_key_2024_very_long_and_secure_key_here
  expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    org.springframework.boot.autoconfigure.security: DEBUG
    com.bookmymovie: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bookmymovie.log